### PR TITLE
Update metadata

### PR DESCRIPTION
**Pull request by joshmoore**
Minor updates to the auto-generated metadata.

### CODE REVIEW

**Comment by joshmoore** [comment]
@manics: this was my first test of migrating a repo for ansible galaxy. Do you see any value in it or shall I get rid of it?

**Comment by manics** [comment]
I haven't used this for a while, but it might or might not be useful for someone less experienced in Ansible.

**Comment by sbesson** [comment]
@joshmoore this repository currently isn't mapped at the organization Ansible Galaxy level. Worth merging, renaming to   `ansible-role-debug-dumpallvars` and tagging as `0.1.0`? Or marking as deprecated?

**Comment by joshmoore** [comment]
Perhaps all the above. I'll do everything except mark deprecated and then we can decide on that.

**Pull request merged**
